# Generated by Django 3.2.8 on 2021-10-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'available_schdules',
            },
        ),
        migrations.CreateModel(
            name='Available_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'available_services',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makername', models.CharField(max_length=40)),
                ('makernickname', models.CharField(max_length=40)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('introduce', models.TextField()),
                ('idcard', models.ImageField(blank=True, null=True, upload_to='idcard/')),
                ('bankbook_image', models.ImageField(blank=True, null=True, upload_to='bankbook/')),
                ('status', models.CharField(max_length=40)),
                ('bank', models.CharField(max_length=45)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('account_holder', models.CharField(max_length=45)),
                ('productform', models.CharField(max_length=45)),
                ('have_car', models.BooleanField(default=False)),
                ('passenger_limit', models.IntegerField(blank=True, null=True)),
                ('available_schedule', models.ManyToManyField(blank=True, to='makers.Available_schedule')),
                ('available_service', models.ManyToManyField(blank=True, to='makers.Available_service')),
                ('category', models.ManyToManyField(blank=True, to='makers.Category')),
                ('language', models.ManyToManyField(blank=True, to='makers.Language')),
            ],
            options={
                'db_table': 'makers',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
            ],
            options={
                'db_table': 'sns',
            },
        ),
        migrations.CreateModel(
            name='Maker_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_people', models.IntegerField()),
                ('limit_load', models.IntegerField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.tour')),
            ],
            options={
                'db_table': 'maker_tours',
            },
        ),
        migrations.AddField(
            model_name='maker',
            name='region',
            field=models.ManyToManyField(blank=True, to='makers.Region'),
        ),
        migrations.AddField(
            model_name='maker',
            name='tour',
            field=models.ManyToManyField(blank=True, through='makers.Maker_tour', to='makers.Tour'),
        ),
        migrations.AddField(
            model_name='maker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='evidence/')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
        migrations.CreateModel(
            name='Contact_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
            ],
            options={
                'db_table': 'contact_channels',
            },
        ),
    ]
