# Generated by Django 3.2.8 on 2021-10-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('makers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makername', models.CharField(blank=True, max_length=40, null=True)),
                ('makernickname', models.CharField(blank=True, max_length=40, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('introduce', models.TextField(blank=True, null=True)),
                ('idcard', models.ImageField(blank=True, null=True, upload_to='idcard/')),
                ('bankbook_image', models.ImageField(blank=True, null=True, upload_to='bankbook/')),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('bank', models.CharField(blank=True, max_length=45, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=45, null=True)),
                ('productform', models.CharField(blank=True, max_length=45, null=True)),
                ('have_car', models.BooleanField(blank=True, default=False, null=True)),
                ('passenger_limit', models.IntegerField(blank=True, null=True)),
                ('available_schedule', models.ManyToManyField(blank=True, null=True, to='makers.Available_schedule')),
                ('available_service', models.ManyToManyField(blank=True, null=True, to='makers.Available_service')),
                ('category', models.ManyToManyField(blank=True, null=True, to='makers.Category')),
                ('language', models.ManyToManyField(blank=True, null=True, to='makers.Language')),
                ('region', models.ManyToManyField(blank=True, null=True, to='makers.Region')),
            ],
            options={
                'db_table': 'draft_makers',
            },
        ),
        migrations.CreateModel(
            name='DraftTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'drafttours',
            },
        ),
        migrations.AlterField(
            model_name='sns',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='DraftMaker_Drafttour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_people', models.IntegerField()),
                ('limit_load', models.IntegerField()),
                ('draftmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.draftmaker')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.drafttour')),
            ],
            options={
                'db_table': 'draftmaker_drafttours',
            },
        ),
        migrations.AddField(
            model_name='draftmaker',
            name='tour',
            field=models.ManyToManyField(blank=True, null=True, through='makers.DraftMaker_Drafttour', to='makers.DraftTour'),
        ),
        migrations.AddField(
            model_name='draftmaker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
