# Generated by Django 3.2.8 on 2021-10-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0002_auto_20211020_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'draftcategories',
            },
        ),
        migrations.CreateModel(
            name='DraftLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'draftlanguages',
            },
        ),
        migrations.CreateModel(
            name='DraftRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'draftregions',
            },
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='makers.DraftCategory'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='makers.DraftLanguage'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='makers.DraftRegion'),
        ),
    ]
