# Generated by Django 3.2.8 on 2021-10-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0003_auto_20211022_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftmaker',
            name='available_schedule',
        ),
        migrations.RemoveField(
            model_name='draftmaker',
            name='available_service',
        ),
        migrations.RemoveField(
            model_name='draftmaker',
            name='have_car',
        ),
        migrations.RemoveField(
            model_name='draftmaker',
            name='passenger_limit',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='available_schedule',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='available_service',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='have_car',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='passenger_limit',
        ),
        migrations.DeleteModel(
            name='Available_schedule',
        ),
        migrations.DeleteModel(
            name='Available_service',
        ),
    ]
