# Generated by Django 3.2.8 on 2021-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0003_auto_20211012_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.ImageField(upload_to='evidence'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='bankbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='bankbook'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='idcard',
            field=models.ImageField(blank=True, null=True, upload_to='idcard'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
