# Generated by Django 3.2.8 on 2021-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0004_auto_20211022_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmaker',
            name='account_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
