# Generated by Django 3.2.8 on 2021-10-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0006_auto_20211022_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmaker',
            name='account_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='draftmaker_drafttour',
            name='limit_load',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='draftmaker_drafttour',
            name='limit_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='account_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
