# Generated by Django 3.2.8 on 2021-10-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0007_auto_20211022_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcategory',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='draftlanguage',
            name='Language',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='draftregion',
            name='region',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='drafttour',
            name='kind',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
