# Generated by Django 3.2.8 on 2021-10-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0008_auto_20211022_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='kind',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='Language',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='account_holder',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='bank',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='makers.Category'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='makers.Language'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='productform',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='makers.Region'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='tour',
            field=models.ManyToManyField(blank=True, null=True, through='makers.Maker_tour', to='makers.Tour'),
        ),
        migrations.AlterField(
            model_name='maker_tour',
            name='limit_load',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maker_tour',
            name='limit_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='kind',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='kind',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='Contact_channel',
        ),
    ]
