# Generated by Django 3.2.8 on 2021-10-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('makers', '0009_auto_20211025_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
