# Generated by Django 3.2.8 on 2021-10-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0010_auto_20211025_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.maker'),
        ),
    ]
