# Generated by Django 3.2.8 on 2021-10-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0011_auto_20211025_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmaker_drafttour',
            name='draftmaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.draftmaker'),
        ),
        migrations.AlterField(
            model_name='draftmaker_drafttour',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.drafttour'),
        ),
        migrations.AlterField(
            model_name='maker_tour',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.maker'),
        ),
        migrations.AlterField(
            model_name='maker_tour',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.tour'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.maker'),
        ),
    ]
