# Generated by Django 3.2.8 on 2021-10-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0012_auto_20211025_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftmaker',
            name='bankbook_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='bankbook/'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='idcard',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='idcard/'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='bankbook_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='bankbook/'),
        ),
        migrations.CreateModel(
            name='DraftEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='evidence/')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
            ],
            options={
                'db_table': 'draftevidences',
            },
        ),
    ]
