# Generated by Django 3.2.8 on 2021-10-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0013_auto_20211025_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftevidence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='bankbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='bankbook/'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='idcard',
            field=models.ImageField(blank=True, null=True, upload_to='idcard/'),
        ),
        migrations.AlterField(
            model_name='draftmaker',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='bankbook_image',
            field=models.ImageField(blank=True, null=True, upload_to='bankbook/'),
        ),
    ]
