# Generated by Django 3.2.8 on 2021-10-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0014_auto_20211026_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftevidence',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.draftmaker'),
        ),
        migrations.CreateModel(
            name='DraftSns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.draftmaker')),
            ],
            options={
                'db_table': 'draftsns',
            },
        ),
    ]
